### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'min_ea'

### ISSUE THREAD

**Issue by W4ZM** [LAC-Japan/IDA_Plugin_AntiDebugSeeker#3]
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA Professional 9.0/plugins/AntiDebugSeeker.py", line 404, in run
    self.detect_anti_debug_functions()
  File "C:/Program Files/IDA Professional 9.0/plugins/AntiDebugSeeker.py", line 659, in detect_anti_debug_functions
    start_addr = idaapi.cvar.inf.min_ea
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'min_ea'

**Comment by takatake-code** [comment]
Thank you for the information. It's very helpful.
This issue has been resolved.
