### ISSUE TITLE
Failed while executing plugin_t.run

### ISSUE THREAD

**Issue by eeeeeeeeeee555** [LAC-Japan/IDA_Plugin_AntiDebugSeeker#4]
when i press ctrl-shift-D, it gave an error: Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA Professional 9.0/plugins/AntiDebugSeeker.py", line 405, in run
    self.detect_anti_debug_functions()
  File "C:/Program Files/IDA Professional 9.0/plugins/AntiDebugSeeker.py", line 676, in detect_anti_debug_functions
    result = self.search_asm(search_keyword)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Program Files/IDA Professional 9.0/plugins/AntiDebugSeeker.py", line 537, in search_asm
    if seg_ea != entry_section.start_ea:
               ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'start_ea'

**Comment by takatake-code** [comment]
Apologies for the delay. 
Could you please provide the hash value of the program where this error occurred?

**Comment by bdd565151** [comment]
i don't understand. Where to find hash value of the program ?

**Comment by takatake-code** [comment]
This tool conducts searches starting from the entrypoint, so if the entrypoint cannot be found, there is a possibility that it may not be able to process.
